"""Build or verify an append-only SQL catalogue migration from places.json."""

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "places.json"
MANIFEST = ROOT / "data" / "seed-migration.txt"
FIELDS = (
    "id", "name", "category", "latitude", "longitude", "region",
    "description", "sourceUrl", "sourceName", "sourceId",
)


def literal(value: object) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, (int, float)):
        return repr(value)
    return "'" + str(value).replace("'", "''") + "'"


def render() -> str:
    places = json.loads(SOURCE.read_text(encoding="utf-8"))
    ids = [place["id"] for place in places]
    if len(ids) != len(set(ids)):
        raise ValueError("Every place id must be unique")
    values = []
    for place in sorted(places, key=lambda item: item["id"]):
        row = [place.get(field) for field in FIELDS]
        values.append("    (" + ", ".join(literal(value) for value in row) + ")")
    sql = "-- Generated by scripts/build_seed_migration.py from data/places.json.\n"
    sql += "-- Missing records are retired, preserving their visit history if later restored.\n"
    sql += "UPDATE places SET active = FALSE;\n\n"
    sql += "INSERT INTO places (id, name, category, latitude, longitude, region, description, source_url, source_name, source_id)\nVALUES\n"
    sql += ",\n".join(values)
    sql += "\nON CONFLICT (id) DO UPDATE SET\n"
    sql += "    name = EXCLUDED.name, category = EXCLUDED.category,\n"
    sql += "    latitude = EXCLUDED.latitude, longitude = EXCLUDED.longitude,\n"
    sql += "    region = EXCLUDED.region, description = EXCLUDED.description,\n"
    sql += "    source_url = EXCLUDED.source_url, source_name = EXCLUDED.source_name,\n"
    sql += "    source_id = EXCLUDED.source_id, active = TRUE;\n"
    return sql


def manifest_target() -> Path:
    relative = MANIFEST.read_text(encoding="utf-8").strip()
    target = (ROOT / relative).resolve()
    if target.parent != (ROOT / "database" / "migrations").resolve():
        raise ValueError("Seed migration manifest must point inside database/migrations")
    return target


def main() -> None:
    parser = argparse.ArgumentParser()
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--check", action="store_true", help="verify JSON matches the current migration")
    group.add_argument("--new", metavar="FILENAME", help="create the next append-only seed migration")
    group.add_argument("--replace-unreleased", action="store_true", help="rewrite the current migration before its first deployment")
    args = parser.parse_args()
    sql = render()

    if args.check:
        target = manifest_target()
        if target.read_text(encoding="utf-8") != sql:
            raise SystemExit(f"{target.relative_to(ROOT)} is stale; create a new numbered seed migration")
        print(f"Verified {target.relative_to(ROOT)} against {SOURCE.relative_to(ROOT)}")
        return

    if args.new:
        if not re.fullmatch(r"\d{4}_[a-z0-9_]+\.sql", args.new):
            raise SystemExit("--new must be a numbered SQL filename such as 0005_refresh_places.sql")
        requested_version = int(args.new[:4])
        existing_versions = [
            int(path.name[:4])
            for path in (ROOT / "database" / "migrations").glob("[0-9][0-9][0-9][0-9]_*.sql")
        ]
        if existing_versions and requested_version <= max(existing_versions):
            raise SystemExit(
                f"New migration version must sort after {max(existing_versions):04d}"
            )
        target = ROOT / "database" / "migrations" / args.new
        if target.exists():
            raise SystemExit(f"Refusing to overwrite existing migration: {target.relative_to(ROOT)}")
        target.write_text(sql, encoding="utf-8", newline="\n")
        MANIFEST.write_text(str(target.relative_to(ROOT)).replace("\\", "/") + "\n", encoding="utf-8", newline="\n")
    else:
        target = manifest_target()
        target.write_text(sql, encoding="utf-8", newline="\n")
    print(f"Wrote {target.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
