export type PlaceImageRecord = {
  src: string;
  alt: string;
  width: number;
  height: number;
  creator: string;
  license: string;
  licenseUrl: string;
  sourceUrl: string;
  sourceTitle: string;
  originalUrl: string;
};

export const PLACE_IMAGES: Readonly<Record<string, PlaceImageRecord>> = {
  "provincial-artlish-caves-park": {
    src: "/places/artlish-caves.webp",
    alt: "Rocky entrance to Artlish River Cave in the forest",
    width: 438,
    height: 648,
    creator: "Ian mckenzie",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Artlish_River_Cave.jpg",
    sourceTitle: "Artlish River Cave",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/9/90/Artlish_River_Cave.jpg",
  },
  "national-pacific-rim-national-park-reserve": {
    src: "/places/pacific-rim.webp",
    alt: "Long Beach and forested headlands in Pacific Rim National Park Reserve",
    width: 560,
    height: 420,
    creator: "Michael Oswald",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Longbeach_prnp.jpg",
    sourceTitle: "Long Beach, Pacific Rim National Park Reserve",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Longbeach_prnp.jpg",
  },
  "national-gulf-islands-national-park-reserve": {
    src: "/places/gulf-islands.webp",
    alt: "Wind-shaped trees at sunset on Sidney Island in Gulf Islands National Park Reserve",
    width: 960,
    height: 640,
    creator: "Michal Klajban",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Trees_during_the_sunset_in_Gulf_Islands_National_Park_Reserve,_Sidney_Island,_BC,_Canada.jpg",
    sourceTitle: "Sunset on Sidney Island, Gulf Islands National Park Reserve",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/6/68/Trees_during_the_sunset_in_Gulf_Islands_National_Park_Reserve%2C_Sidney_Island%2C_BC%2C_Canada.jpg",
  },
  "provincial-cape-scott-park": {
    src: "/places/cape-scott.webp",
    alt: "Hikers beneath the Cape Scott Provincial Park trailhead sign",
    width: 960,
    height: 720,
    creator: "David Stanley",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cape_Scott_Provincial_Park_(28693304363).jpg",
    sourceTitle: "Cape Scott Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/3/35/Cape_Scott_Provincial_Park_%2828693304363%29.jpg",
  },
  "provincial-strathcona-park": {
    src: "/places/strathcona.webp",
    alt: "Mountain meadow and boardwalk in Paradise Meadows, Strathcona Provincial Park",
    width: 960,
    height: 1280,
    creator: "Susan Daly",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Paradise_Meadows_Strathcona_Provincial_Park_02.jpg",
    sourceTitle: "Paradise Meadows, Strathcona Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/1/15/Paradise_Meadows_Strathcona_Provincial_Park_02.jpg",
  },
  "provincial-juan-de-fuca-park": {
    src: "/places/juan-de-fuca.webp",
    alt: "Wooden footbridge on the Juan de Fuca Marine Trail",
    width: 960,
    height: 640,
    creator: "Colin Stepney",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:JDFBridge.jpg",
    sourceTitle: "Bridge on the Juan de Fuca Marine Trail",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4b/JDFBridge.jpg",
  },
  "provincial-goldstream-park": {
    src: "/places/goldstream.webp",
    alt: "Goldstream River flowing between mossy forest banks",
    width: 960,
    height: 1280,
    creator: "Mike",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Flow,_Goldstream_Provincial_Park.jpg",
    sourceTitle: "Flow, Goldstream Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Flow%2C_Goldstream_Provincial_Park.jpg",
  },
  "provincial-rathtrevor-beach-park": {
    src: "/places/rathtrevor-beach.webp",
    alt: "Wide sandy shoreline at Rathtrevor Beach Provincial Park",
    width: 960,
    height: 640,
    creator: "marneejill",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rathtrevor_Beach_Provincial_Park.jpg",
    sourceTitle: "Rathtrevor Beach Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Rathtrevor_Beach_Provincial_Park.jpg",
  },
  "provincial-englishman-river-falls-park": {
    src: "/places/englishman-river-falls.webp",
    alt: "Waterfall cascading through Englishman River Falls Provincial Park",
    width: 960,
    height: 1282,
    creator: "LizinVictoria",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Englishman_River_Falls_Provincial_Park.jpg",
    sourceTitle: "Englishman River Falls Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Englishman_River_Falls_Provincial_Park.jpg",
  },
  "provincial-little-qualicum-falls-park": {
    src: "/places/little-qualicum-falls.webp",
    alt: "Little Qualicum Falls tumbling through a rocky gorge",
    width: 960,
    height: 1440,
    creator: "GoToVan",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Little_Qualicum_Falls_Provincial_Park_(36676055632).jpg",
    sourceTitle: "Little Qualicum Falls Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Little_Qualicum_Falls_Provincial_Park_%2836676055632%29.jpg",
  },
  "provincial-elk-falls-park": {
    src: "/places/elk-falls.webp",
    alt: "Elk Falls and suspension bridge above the canyon",
    width: 960,
    height: 1280,
    creator: "dvs",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Elk_Falls_and_the_swinging_bridge_(48822254148).jpg",
    sourceTitle: "Elk Falls and the suspension bridge",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Elk_Falls_and_the_swinging_bridge_%2848822254148%29.jpg",
  },
  "provincial-carmanah-walbran-park": {
    src: "/places/carmanah-walbran.webp",
    alt: "Carmanah Walbran Provincial Park sign among old-growth trees",
    width: 960,
    height: 640,
    creator: "Adam Walker",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Carmanah_walbran_park.jpg",
    sourceTitle: "Carmanah Walbran Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Carmanah_walbran_park.jpg",
  },
  "provincial-horne-lake-caves-park": {
    src: "/places/horne-lake-caves.webp",
    alt: "Layered rock walls inside the lower Horne Lake cave",
    width: 681,
    height: 1024,
    creator: "Dave Bunnell",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Horne_lake_lower_cave.jpg",
    sourceTitle: "Horne Lake lower cave",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/7/72/Horne_lake_lower_cave.jpg",
  },
  "provincial-sooke-potholes-park": {
    src: "/places/sooke-potholes.webp",
    alt: "Clear river pools and sculpted rock at Sooke Potholes Provincial Park",
    width: 960,
    height: 1282,
    creator: "Ruth Hartnup",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Potholes-SPPP.jpg",
    sourceTitle: "Sooke Potholes Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Potholes-SPPP.jpg",
  },
  "provincial-macmillan-park": {
    src: "/places/macmillan.webp",
    alt: "Visitor beside a giant old-growth tree in Cathedral Grove, MacMillan Provincial Park",
    width: 960,
    height: 1434,
    creator: "Aaron Carlson",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:CathedralGrove-VancouverIsland.jpg",
    sourceTitle: "Cathedral Grove, MacMillan Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/f/ff/CathedralGrove-VancouverIsland.jpg",
  },
  "provincial-saysutshun-newcastle-island-marine-park": {
    src: "/places/saysutshun-newcastle.webp",
    alt: "Beach and driftwood on Saysutshun, Newcastle Island Marine Provincial Park",
    width: 960,
    height: 638,
    creator: "Kristina D.C. Hoeppner",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Newcastle_Island_beach_(28994072520).jpg",
    sourceTitle: "Newcastle Island beach",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/3/36/Newcastle_Island_beach_%2828994072520%29.jpg",
  },
  "regional-east-sooke-regional-park": {
    src: "/places/east-sooke.webp",
    alt: "Rocky shoreline and forest in East Sooke Regional Park",
    width: 960,
    height: 642,
    creator: "Brandon Godfrey",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:East_Sooke_Park_BC.jpg",
    sourceTitle: "East Sooke Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/East_Sooke_Park_BC.jpg",
  },
};

export const PLACE_IMAGE_COUNT = Object.keys(PLACE_IMAGES).length;

export function getPlaceImage(placeId: string): PlaceImageRecord | undefined {
  return PLACE_IMAGES[placeId];
}
