import cataloguePlaceImages from "./place-images.catalogue.json";

export type PlaceImageAsset = {
  src: string;
  width: number;
  height: number;
};

export type PlaceImageRecord = {
  thumbnail: PlaceImageAsset;
  detail: PlaceImageAsset;
  alt: string;
  creator: string;
  license: string;
  licenseUrl: string;
  sourceUrl: string;
  sourceTitle: string;
  originalUrl: string;
  locationEvidence: string;
  locationEvidenceUrl: string;
  changes: string;
};

const CHANGES = "Resized without upscaling, converted to WebP, and center-cropped by the interface when needed.";

const BASE_PLACE_IMAGES: Readonly<Record<string, PlaceImageRecord>> = {
  "provincial-artlish-caves-park": {
    thumbnail: { src: "/places/artlish-caves-thumb.webp", width: 320, height: 474 },
    detail: { src: "/places/artlish-caves.webp", width: 438, height: 648 },
    alt: "Rocky entrance to Artlish River Cave in the forest",
    creator: "Ian mckenzie",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Artlish_River_Cave.jpg",
    sourceTitle: "Artlish River Cave",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/9/90/Artlish_River_Cave.jpg",
    locationEvidence: "The Commons description identifies the entrance to Artlish River Cave on Vancouver Island.",
    locationEvidenceUrl: "https://bcparks.ca/artlish-caves-park/",
    changes: CHANGES,
  },
  "national-pacific-rim-national-park-reserve": {
    thumbnail: { src: "/places/pacific-rim-thumb.webp", width: 320, height: 240 },
    detail: { src: "/places/pacific-rim.webp", width: 560, height: 420 },
    alt: "Long Beach and forested headlands in Pacific Rim National Park Reserve",
    creator: "Michael Oswald",
    license: "Public domain",
    licenseUrl: "https://creativecommons.org/publicdomain/mark/1.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Longbeach_prnp.jpg",
    sourceTitle: "Long Beach, Pacific Rim National Park Reserve",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/9/93/Longbeach_prnp.jpg",
    locationEvidence: "The Commons file description identifies Long Beach in Pacific Rim National Park Reserve.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:Longbeach_prnp.jpg",
    changes: CHANGES,
  },
  "national-gulf-islands-national-park-reserve": {
    thumbnail: { src: "/places/gulf-islands-thumb.webp", width: 320, height: 214 },
    detail: { src: "/places/gulf-islands.webp", width: 960, height: 640 },
    alt: "Wind-shaped trees at sunset on Sidney Island in Gulf Islands National Park Reserve",
    creator: "Michal Klajban",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Trees_during_the_sunset_in_Gulf_Islands_National_Park_Reserve,_Sidney_Island,_BC,_Canada.jpg",
    sourceTitle: "Sunset on Sidney Island, Gulf Islands National Park Reserve",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/6/68/Trees_during_the_sunset_in_Gulf_Islands_National_Park_Reserve%2C_Sidney_Island%2C_BC%2C_Canada.jpg",
    locationEvidence: "The Commons description names Sidney Island in Gulf Islands National Park Reserve.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:Trees_during_the_sunset_in_Gulf_Islands_National_Park_Reserve,_Sidney_Island,_BC,_Canada.jpg",
    changes: CHANGES,
  },
  "provincial-cape-scott-park": {
    thumbnail: { src: "/places/cape-scott-thumb.webp", width: 320, height: 240 },
    detail: { src: "/places/cape-scott.webp", width: 960, height: 720 },
    alt: "Hikers beneath the Cape Scott Provincial Park trailhead sign",
    creator: "David Stanley",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Cape_Scott_Provincial_Park_(28693304363).jpg",
    sourceTitle: "Cape Scott Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/3/35/Cape_Scott_Provincial_Park_%2828693304363%29.jpg",
    locationEvidence: "The Commons description identifies Cape Scott Provincial Park at Vancouver Island's northwest end.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:Cape_Scott_Provincial_Park_(28693304363).jpg",
    changes: CHANGES,
  },
  "provincial-strathcona-park": {
    thumbnail: { src: "/places/strathcona-thumb.webp", width: 320, height: 426 },
    detail: { src: "/places/strathcona.webp", width: 960, height: 1280 },
    alt: "Mountain meadow and boardwalk in Paradise Meadows, Strathcona Provincial Park",
    creator: "Susan Daly",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Paradise_Meadows_Strathcona_Provincial_Park_02.jpg",
    sourceTitle: "Paradise Meadows, Strathcona Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/1/15/Paradise_Meadows_Strathcona_Provincial_Park_02.jpg",
    locationEvidence: "The Commons description and title identify Strathcona Provincial Park and Paradise Meadows.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:Paradise_Meadows_Strathcona_Provincial_Park_02.jpg",
    changes: CHANGES,
  },
  "provincial-juan-de-fuca-park": {
    thumbnail: { src: "/places/juan-de-fuca-thumb.webp", width: 320, height: 214 },
    detail: { src: "/places/juan-de-fuca.webp", width: 960, height: 640 },
    alt: "Wooden footbridge on the Juan de Fuca Marine Trail",
    creator: "Colin Stepney",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:JDFBridge.jpg",
    sourceTitle: "Bridge on the Juan de Fuca Marine Trail",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/4/4b/JDFBridge.jpg",
    locationEvidence: "The Commons description places the bridge in Juan de Fuca Provincial Park between Mystic and Bear beaches.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:JDFBridge.jpg",
    changes: CHANGES,
  },
  "provincial-goldstream-park": {
    thumbnail: { src: "/places/goldstream-thumb.webp", width: 320, height: 426 },
    detail: { src: "/places/goldstream.webp", width: 960, height: 1280 },
    alt: "Goldstream River flowing between mossy forest banks",
    creator: "Mike",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Flow,_Goldstream_Provincial_Park.jpg",
    sourceTitle: "Flow, Goldstream Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fb/Flow%2C_Goldstream_Provincial_Park.jpg",
    locationEvidence: "The Commons description identifies Goldstream Provincial Park on Vancouver Island.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:Flow,_Goldstream_Provincial_Park.jpg",
    changes: CHANGES,
  },
  "provincial-rathtrevor-beach-park": {
    thumbnail: { src: "/places/rathtrevor-beach-thumb.webp", width: 320, height: 214 },
    detail: { src: "/places/rathtrevor-beach.webp", width: 960, height: 640 },
    alt: "Wide sandy shoreline at Rathtrevor Beach Provincial Park",
    creator: "marneejill",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Rathtrevor_Beach_Provincial_Park.jpg",
    sourceTitle: "Rathtrevor Beach Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/0/0c/Rathtrevor_Beach_Provincial_Park.jpg",
    locationEvidence: "The Commons description identifies Rathtrevor Beach Provincial Park in Parksville.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:Rathtrevor_Beach_Provincial_Park.jpg",
    changes: CHANGES,
  },
  "provincial-englishman-river-falls-park": {
    thumbnail: { src: "/places/englishman-river-falls-thumb.webp", width: 320, height: 428 },
    detail: { src: "/places/englishman-river-falls.webp", width: 960, height: 1282 },
    alt: "Waterfall cascading through Englishman River Falls Provincial Park",
    creator: "LizinVictoria",
    license: "CC BY-SA 4.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/4.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Englishman_River_Falls_Provincial_Park.jpg",
    sourceTitle: "Englishman River Falls Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/6/6a/Englishman_River_Falls_Provincial_Park.jpg",
    locationEvidence: "The Commons category and file title identify Englishman River Falls Provincial Park.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:Englishman_River_Falls_Provincial_Park.jpg",
    changes: CHANGES,
  },
  "provincial-little-qualicum-falls-park": {
    thumbnail: { src: "/places/little-qualicum-falls-thumb.webp", width: 320, height: 480 },
    detail: { src: "/places/little-qualicum-falls.webp", width: 960, height: 1440 },
    alt: "Little Qualicum Falls tumbling through a rocky gorge",
    creator: "GoToVan",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Little_Qualicum_Falls_Provincial_Park_(36676055632).jpg",
    sourceTitle: "Little Qualicum Falls Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a9/Little_Qualicum_Falls_Provincial_Park_%2836676055632%29.jpg",
    locationEvidence: "The Commons description and category identify Little Qualicum Falls Provincial Park.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:Little_Qualicum_Falls_Provincial_Park_(36676055632).jpg",
    changes: CHANGES,
  },
  "provincial-elk-falls-park": {
    thumbnail: { src: "/places/elk-falls-thumb.webp", width: 320, height: 426 },
    detail: { src: "/places/elk-falls.webp", width: 960, height: 1280 },
    alt: "Elk Falls and suspension bridge above the canyon",
    creator: "dvs",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Elk_Falls_and_the_swinging_bridge_(48822254148).jpg",
    sourceTitle: "Elk Falls and the suspension bridge",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/a/a0/Elk_Falls_and_the_swinging_bridge_%2848822254148%29.jpg",
    locationEvidence: "The Commons description names Elk Falls and its category identifies Elk Falls Provincial Park.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:Elk_Falls_and_the_swinging_bridge_(48822254148).jpg",
    changes: CHANGES,
  },
  "provincial-carmanah-walbran-park": {
    thumbnail: { src: "/places/carmanah-walbran-thumb.webp", width: 320, height: 214 },
    detail: { src: "/places/carmanah-walbran.webp", width: 960, height: 640 },
    alt: "Carmanah Walbran Provincial Park sign among old-growth trees",
    creator: "Adam Walker",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Carmanah_walbran_park.jpg",
    sourceTitle: "Carmanah Walbran Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/2/21/Carmanah_walbran_park.jpg",
    locationEvidence: "The Commons description identifies the sign at Carmanah Walbran Provincial Park.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:Carmanah_walbran_park.jpg",
    changes: CHANGES,
  },
  "provincial-horne-lake-caves-park": {
    thumbnail: { src: "/places/horne-lake-caves-thumb.webp", width: 320, height: 482 },
    detail: { src: "/places/horne-lake-caves.webp", width: 681, height: 1024 },
    alt: "Layered rock walls inside the lower Horne Lake cave",
    creator: "Dave Bunnell",
    license: "CC BY-SA 3.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/3.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Horne_lake_lower_cave.jpg",
    sourceTitle: "Horne Lake lower cave",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/7/72/Horne_lake_lower_cave.jpg",
    locationEvidence: "The Commons description identifies the Lower Cave at Horne Lake Caves Provincial Park.",
    locationEvidenceUrl: "https://bcparks.ca/horne-lake-caves-park/",
    changes: CHANGES,
  },
  "provincial-sooke-potholes-park": {
    thumbnail: { src: "/places/sooke-potholes-thumb.webp", width: 320, height: 428 },
    detail: { src: "/places/sooke-potholes.webp", width: 960, height: 1282 },
    alt: "Clear river pools and sculpted rock at Sooke Potholes Provincial Park",
    creator: "Ruth Hartnup",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Potholes-SPPP.jpg",
    sourceTitle: "Sooke Potholes Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Potholes-SPPP.jpg",
    locationEvidence: "The Commons description identifies Sooke Potholes at Sooke Potholes Provincial Park.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:Potholes-SPPP.jpg",
    changes: CHANGES,
  },
  "provincial-macmillan-park": {
    thumbnail: { src: "/places/macmillan-thumb.webp", width: 320, height: 478 },
    detail: { src: "/places/macmillan.webp", width: 960, height: 1434 },
    alt: "Visitor beside a giant old-growth tree in Cathedral Grove, MacMillan Provincial Park",
    creator: "Aaron Carlson",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:CathedralGrove-VancouverIsland.jpg",
    sourceTitle: "Cathedral Grove, MacMillan Provincial Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/f/ff/CathedralGrove-VancouverIsland.jpg",
    locationEvidence: "The Commons description names Cathedral Grove and categorizes the image under MacMillan Provincial Park.",
    locationEvidenceUrl: "https://bcparks.ca/macmillan-park/",
    changes: CHANGES,
  },
  "provincial-saysutshun-newcastle-island-marine-park": {
    thumbnail: { src: "/places/saysutshun-newcastle-thumb.webp", width: 320, height: 212 },
    detail: { src: "/places/saysutshun-newcastle.webp", width: 960, height: 638 },
    alt: "Beach and driftwood on Saysutshun, Newcastle Island Marine Provincial Park",
    creator: "Kristina D.C. Hoeppner",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Newcastle_Island_beach_(28994072520).jpg",
    sourceTitle: "Newcastle Island beach",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/3/36/Newcastle_Island_beach_%2828994072520%29.jpg",
    locationEvidence: "The Commons description names Newcastle Island beach and categorizes it under the marine provincial park.",
    locationEvidenceUrl: "https://bcparks.ca/saysutshun-newcastle-island-marine-park/",
    changes: CHANGES,
  },
  "regional-east-sooke-regional-park": {
    thumbnail: { src: "/places/east-sooke-thumb.webp", width: 320, height: 214 },
    detail: { src: "/places/east-sooke.webp", width: 960, height: 642 },
    alt: "Rocky shoreline and forest in East Sooke Regional Park",
    creator: "Brandon Godfrey",
    license: "CC BY-SA 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by-sa/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:East_Sooke_Park_BC.jpg",
    sourceTitle: "East Sooke Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/e/e8/East_Sooke_Park_BC.jpg",
    locationEvidence: "The Commons description identifies East Sooke Regional Park and its protected coastal landscape.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:East_Sooke_Park_BC.jpg",
    changes: CHANGES,
  },
  "regional-little-huson-cave-regional-park": {
    thumbnail: { src: "/places/little-huson-thumb.webp", width: 320, height: 240 },
    detail: { src: "/places/little-huson.webp", width: 960, height: 720 },
    alt: "Atluck Creek flowing from beneath the natural bridge in Little Huson Cave Regional Park",
    creator: "David Stanley",
    license: "CC BY 2.0",
    licenseUrl: "https://creativecommons.org/licenses/by/2.0/",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Natural_Bridge_(28723312295).jpg",
    sourceTitle: "Natural Bridge in Little Huson Regional Park",
    originalUrl: "https://upload.wikimedia.org/wikipedia/commons/f/f7/Natural_Bridge_%2828723312295%29.jpg",
    locationEvidence: "The Commons description and coordinates identify Atluck Creek and the natural bridge inside Little Huson Regional Park on Vancouver Island.",
    locationEvidenceUrl: "https://commons.wikimedia.org/wiki/File:Natural_Bridge_(28723312295).jpg",
    changes: CHANGES,
  },
};

export const PLACE_IMAGES: Readonly<Record<string, PlaceImageRecord>> = {
  ...BASE_PLACE_IMAGES,
  ...(cataloguePlaceImages as Record<string, PlaceImageRecord>),
};

export const PLACE_IMAGE_COUNT = Object.keys(PLACE_IMAGES).length;

export function getPlaceImage(placeId: string): PlaceImageRecord | undefined {
  return PLACE_IMAGES[placeId];
}
